name: Rust 2023

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: cargo build --verbose
        working-directory: 2023/Rust

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: cargo test --verbose
        working-directory: 2023/Rust

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Clippy
        uses: actions-rs/clippy-check@v1.0.7
        with:
          working-directory: 2023/Rust

      - name: Format Check
        uses: actions-rust-lang/rustfmt@v1.1.0
        with:
          working-directory: 2023/Rust
