name: Rust 2023

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: cargo build --verbose
        working-directory: 2023/Rust

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: cargo test --verbose
        working-directory: 2023/Rust

  format:
    name: "cargo fmt"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Install Rust toolchain"
        run: rustup component add rustfmt

      - run: cargo fmt --all --check
        working-directory: 2023/Rust

  clippy:
    name: "cargo clippy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Install Rust toolchain"
        run: |
          rustup component add clippy

      - uses: Swatinem/rust-cache@v2

      - name: "Clippy"
        run: cargo clippy
        working-directory: 2023/Rust
